config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  get 'home/index'
  get 'home/show'

  resources :keyword_replies

  post '/callback', to: 'linebot#callback'
end

app/models/a3rt.rb
class A3rt < ApplicationRecord
  def self.talk(message)
    uri_path = 'https://api.a3rt.recruit-tech.co.jp/talk/v1/smalltalk'
    query_string = { 'apikey' => ENV['A3RT_API_KEY'], 'query' => message }

    NetUtil.post_request(uri_path, query_string)
  end
end

app/models/annict.rb
class Annict < ApplicationRecord
  def self.fetch(target_season)
    uri_path = "https://api.annict.com/v1/works?fields=title&per_page=50&filter_season=#{target_season}&sort_watchers_count=desc&access_token=#{ENV['ANNICT_ACCESS_TOKEN']}"
    NetUtil.http_request(uri_path, true)
  end

  def self.parse_msg(body)
    result = JSON.parse(body)
    anime_list = ''
    result['works'].each do |item|
      anime_list += "#{item['title']} \n"
    end
    anime_list
  end

  def self.error_msg(res)
    "[#{response.code}] アニメ情報のの取得に失敗しました #{response.message}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/keyword_reply.rb
class KeywordReply < ApplicationRecord
  def self.fetch(keyword)
    KeywordReply.find_by(keyword: keyword)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :recoverable, :trackable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
end

app/models/weather.rb
class Weather < ApplicationRecord
  def self.fetch
    uri_path = 'http://weather.livedoor.com/forecast/webservice/json/v1?city=130010'
    NetUtil.http_request(uri_path, false)
  end

  def self.parse_msg(body)
    result = JSON.parse(body)
    forecastList = result['forecasts']
    temperatureInfo = "\n----------\n"
    forecastList.each do |forecast|
      temperatureInfo += "#{forecast['date']}(#{forecast['dateLabel']})"
      temperatureInfo += "    天気 : #{forecast['telop']}\n"
      temperatureInfo += "    気温 : 最高気温 #{forecast['temperature']['max']['celsius']}℃" if forecast['temperature']['max']
      temperatureInfo += ' / ' + " 最低気温 #{forecast['temperature']['min']['celsius']}℃" if forecast['temperature']['min']
      temperatureInfo += "\n"
    end
    description = result['description']['text'].split(/\s*【東京地方】\s*/)
    result['title'] + "\n\n " + description[1] + temperatureInfo
  end

  def self.error_msg(res)
    "[#{response.code}] 天気の取得に失敗しました #{response.message}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def show; end
end

app/controllers/keyword_replies_controller.rb
class KeywordRepliesController < ApplicationController
  before_filter :basic_auth

  def index
    @keyword_replies = KeywordReply.all
  end

  def show
    @keyword_reply = KeywordReply.find(params[:id])
  end

  def new
    @keyword_reply = KeywordReply.new
  end

  def edit
    @keyword_reply = KeywordReply.find(params[:id])
  end

  def create
    @keyword_reply = KeywordReply.new(keyword_reply_params)

    respond_to do |format|
      if @keyword_reply.save
        format.html { redirect_to @keyword_reply, notice: 'KeywordReply was successfully created.' }
        format.json { render :show, status: :created, location: @keyword_reply }
      else
        format.html { render :new }
        format.json { render json: @keyword_reply.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @keyword_reply = KeywordReply.find(params[:id])
    respond_to do |format|
      if @keyword_reply.update(keyword_reply_params)
        format.html { redirect_to @keyword_reply, notice: 'KeywordReply was successfully updated.' }
        format.json { render :show, status: :created, location: @keyword_reply }
      else
        format.html { render :new }
        format.json { render json: @keyword_reply.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @keyword_reply = KeywordReply.find(params[:id])
    @keyword_reply.destroy
    respond_to do |format|
      format.html { redirect_to keyword_replies_url, notice: 'KeywordReply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def basic_auth
    authenticate_or_request_with_http_basic do |user, pass|
      user == ENV['BASIC_AUTH_USER'] && pass == ENV['BASIC_AUTH_PASS']
    end
  end

  def keyword_reply_params
    params.require(:keyword_reply).permit(:keyword, :reply_type, :reply_word)
  end
end

app/controllers/linebot_controller.rb
require 'line/bot'
require 'net/http'
require 'uri'
require 'rexml/document'

class LinebotController < ApplicationController
  protect_from_forgery except: ['callback']

  def callback
    message = {
      type: 'text',
      text: 'Hello, This is LINE bot'
    }
    client = Line::Bot::Client.new do |config|
      config.channel_secret = ENV['LINE_CHANNEL_SECRET']
      config.channel_token = ENV['LINE_CHANNEL_TOKEN']
    end

    puts events = client.parse_events_from(request.body.read)

    events.each do |event|
      case event
      when Line::Bot::Event::Message
        case event.type
        when Line::Bot::Event::MessageType::Text
          keyword_reply = KeywordReply.fetch(event['message']['text'])
          if !keyword_reply.nil?
            message['text'] = keyword_reply.reply_word
          elsif event['message']['text'].include?('とは')
            target_word = event['message']['text'].sub(/とは/, '')
            message['text'] = search_word(target_word)
          elsif event['message']['text'].include?(ENV['BOT_NAME'])
            target_word = event['message']['text'].sub(ENV['BOT_NAME'], '')
            message['text'] = talk_bot(target_word)
          else
            case event['message']['text']
            when '天気'
              message['text'] = fetch_weather
            when 'アニメ一覧'
              target_season = DateUtil.detect_target_season
              message['text'] = fetch_anime(target_season)
            when 'こんにちは'
              message['text'] = greet(client, event['source']['userId'])
            when 'ポエム'
              message['text'] = PoemUtil.select_poem
            else
              return
            end
          end
          response = client.reply_message(event['replyToken'], message)
          p response.body
        end
      end
    end
  end

  def fetch_weather
    response = Weather.fetch

    if response.code == '200'
      return Weather.parse_msg(response.body)
    else
      return Weather.error_msg(response)
    end
  end

  def fetch_anime(target_season)
    response = Annict.fetch(target_season)
    if response.code == '200'
      return Annict.parse_msg(response.body)
    else
      return Annict.error_msg(response)
    end
  end

  def talk_bot(message)
    response = A3rt.talk(message)
    body = JSON.parse(response.body)
    if body['status'].zero?
      return body['results'][0]['reply']
    else
      return body['message']
    end
  end

  def search_word(target_word)
    uri_path = "http://wikipedia.simpleapi.net/api?keyword=#{target_word}&output=json"
    response = NetUtil.http_request(uri_path, false)
    if response.code == '200'
      content = JSON.parse(response.body)
      result  = "【#{content[0]['title']}】\n"
      result += content[0]['body']
    else
      puts 'ERROR'
    end
  end

  def greet(client, userId)
    resProfile = client.get_profile(userId)
    case resProfile
    when Net::HTTPSuccess then
      contact = JSON.parse(resProfile.body)
      p contact['displayName'] + contact['pictureUrl'] + contact['statusMessage']
      return "#{contact['displayName']}さん こんにちは♪"
    else
      return "#{resProfile.code} #{resProfile.body}"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/keyword_replies_helper.rb
module KeywordRepliesHelper
end

app/views/home/index.html.slim
p
  | これは LINE Bot 管理画面です
= link_to 'メッセージ登録画面へ', keyword_replies_path

app/views/home/show.html.slim
h1
  | Home#show
p
  | Find me in app/views/home/show.html.erb

app/views/keyword_replies/edit.html.slim
h1
  | 編集
.form-horizontal[role="form"]
  = form_for(@keyword_reply) do |form|
    .form-group
      = form.label :'キーワード', class: 'col-sm-3 control-label'
      .col-sm-7
        = form.text_field :keyword, class: 'form-control'
    .form-group
      = form.label :'応答タイプ', class: 'col-sm-3 control-label'
      .col-sm-7
        = form.select :reply_type, [['text', 'text']], class: 'form-control'
    .form-group
      = form.label :'応答メッセージ', class: 'col-sm-3 control-label'
      .col-sm-7
        = form.text_field :reply_word, class: 'form-control'
    .form-group
      .col-sm-offset-3.col-sm-10
        = form.submit "編集", class: 'btn btn-primary'

app/views/keyword_replies/index.html.slim
h1
  | キーワード応答メッセージ一覧
= button_to '新規キーワード追加', new_keyword_reply_path, method: :get, class: 'btn btn-primary'
table.table.table-hover
  tr
    th
      | キーワード
    th
      | 応答タイプ
    th
      | 応答メッセージ
    th

  tbody
    - @keyword_replies.each do |keyword_reply|
      tr
        td
          = keyword_reply.keyword
        td
          = keyword_reply.reply_type
        td
          = keyword_reply.reply_word
        td
          = link_to '詳細', keyword_reply

app/views/keyword_replies/new.html.slim
h1
  | 新規作成
.form-horizontal[role="form"]
  = form_for(@keyword_reply) do |form|
    .form-group
      = form.label :'キーワード', class: 'col-sm-3 control-label'
      .col-sm-7
        = form.text_field :keyword, class: 'form-control'
    .form-group
      = form.label :'応答タイプ', class: 'col-sm-3 control-label'
      .col-sm-7
        = form.select :reply_type, [['text', 'text']], class: 'form-control'
    .form-group
      = form.label :'応答メッセージ', class: 'col-sm-3 control-label'
      .col-sm-7
        = form.text_field :reply_word, class: 'form-control'
    .form-group
      .col-sm-offset-3.col-sm-10
        = form.submit "作成", class: 'btn btn-primary'

app/views/keyword_replies/show.html.slim
h1
  = @keyword_reply.keyword
  |  詳細画面
table.table.table-hover
  tr
    th
      | キーワード
    th
      | 応答タイプ
    th
      | 応答メッセージ
    th

    th

  tbody
    tr
      td
        = @keyword_reply.keyword
      td
        = @keyword_reply.reply_type
      td
        = @keyword_reply.reply_word
      td
        = link_to '編集', edit_keyword_reply_path(@keyword_reply)
      td
        = link_to '削除', @keyword_reply, method: :delete, data: { confirm: 'Are you sure?' }
= link_to 'キーワード応答一覧', keyword_replies_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | SwallowTail
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    nav.navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          = link_to 'SwallowTail', root_path, class: 'navbar-brand'
    .container
      = yield